name: rhofold_protocol
channels:
  - bioconda
  - esri
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - absl-py=2.1.0=py310h06a4308_0
  - biopython=1.85=py310ha75aee5_1
  - blosc=1.21.5=hc2324a3_1
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.2.25=h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.1=py310h3788b33_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - einops=0.7.0=py_1
  - expat=2.6.4=h5888daf_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.56.0=py310h89163eb_0
  - freetype=2.12.1=h4a9f257_0
  - glew=2.1.0=h295c915_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glm=0.9.9.8=h00ab1b0_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - icu=73.1=h6a678d5_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - jpeg=9e=h0b41bf4_3
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - kiwisolver=1.4.7=py310h3788b33_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libaec=1.1.3=h6a678d5_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=31_he106b2a_openblas
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.78.4=hdc74915_0
  - libglu=9.0.0=hf484d3e_1
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - libllvm14=14.0.6=hecde1de_4
  - libnetcdf=4.9.2=nompi_h135f659_114
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.43=h2797004_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.5.1=hffd6297_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxkbcommon=1.8.0=hc4a0caf_0
  - libxml2=2.13.5=hfdd30dd_0
  - libxslt=1.1.41=h097e994_0
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=h4ab18f5_6
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.10.1=py310hff52083_0
  - matplotlib-base=3.10.1=py310h68603db_0
  - minizip=4.0.3=hf59b114_0
  - ml-collections=1.0.0=pyh29332c3_0
  - munkres=1.0.7=py_1
  - mysql=8.4.0=h29a9f33_1
  - ncurses=6.4=h6a678d5_0
  - nspr=4.36=h5888daf_0
  - nss=3.89.1=h6a678d5_0
  - numpy=2.2.3=py310hefbff90_0
  - ocl-icd=2.3.2=h5eee18b_1
  - ocl-icd-system=1.0.0=1
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openmm=8.2.0=py310h30bdd6a_2
  - openssl=3.4.1=h7b32b05_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py310h5eaa309_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py310hcea889d_0
  - pip=25.0=py310h06a4308_0
  - pmw=2.0.1=py310hff52083_1008
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pymol-open-source=3.0.0=py310h200f838_8
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pyqt=6.7.1=py310h6a678d5_0
  - pyqt6-sip=13.9.1=py310h5eee18b_0
  - pyside6=6.7.2=py310ha2c6bb1_0
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - qhull=2020.2=h4bd325d_2
  - qtbase=6.7.2=hdaa5aa8_1
  - qtdeclarative=6.7.2=h6a678d5_0
  - qtshadertools=6.7.2=h6a678d5_0
  - qtsvg=6.7.2=he621ea3_0
  - qttools=6.7.2=h80c7b02_0
  - qtwebchannel=6.7.2=h6a678d5_0
  - qtwebengine=6.7.2=hcbda680_0
  - qtwebsockets=6.7.2=h6a678d5_0
  - readline=8.2=h5eee18b_0
  - scikit-learn=1.6.1=py310h27f47ee_0
  - scipy=1.15.2=py310h1d65ade_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=75.8.0=py310h06a4308_0
  - sip=6.10.0=py310h6a678d5_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - statsmodels=0.14.4=py310hf462985_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py310h06a4308_0
  - tornado=6.4.2=py310ha75aee5_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tzdata=2025a=h04d1e81_0
  - unicodedata2=16.0.0=py310ha75aee5_0
  - usalign=2024.07.30=h503566f_1
  - wheel=0.45.1=py310h06a4308_0
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - filelock==3.18.0
      - fsspec==2025.3.0
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - ptflops==0.7.4
      - rna-fm==0.2.2
      - sympy==1.13.1
      - torch==2.6.0
      - triton==3.2.0
      - typing-extensions==4.12.2
prefix: /workspace/jmwang/.conda/envs/rhofold_protocol
